//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseGradeEstimator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseGradeEstimator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongodb://{0}:{1}@ds129906.mlab.com:29906/.
        /// </summary>
        internal static string AppDBConnectionString {
            get {
                return ResourceManager.GetString("AppDBConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ead-cw2.
        /// </summary>
        internal static string AppDBName {
            get {
                return ResourceManager.GetString("AppDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr4d3:P$%%.
        /// </summary>
        internal static string AppDBPass {
            get {
                return ResourceManager.GetString("AppDBPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gradeApp.
        /// </summary>
        internal static string AppDBUser {
            get {
                return ResourceManager.GetString("AppDBUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseGradeEstimator.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string AppResourceTypeCourse {
            get {
                return ResourceManager.GetString("AppResourceTypeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string AppResourceTypeGrade {
            get {
                return ResourceManager.GetString("AppResourceTypeGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Grade Estimator.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string ViewCreateCourseHeader {
            get {
                return ResourceManager.GetString("ViewCreateCourseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool allows you to enter information about a course and then assign grades to assessments in order to determin your predicted grade..
        /// </summary>
        internal static string ViewStartDescription {
            get {
                return ResourceManager.GetString("ViewStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string ViewStartExitButtonText {
            get {
                return ResourceManager.GetString("ViewStartExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Course.
        /// </summary>
        internal static string ViewStartStartButtonText {
            get {
                return ResourceManager.GetString("ViewStartStartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0}.
        /// </summary>
        internal static string ViewStartSubTitle {
            get {
                return ResourceManager.GetString("ViewStartSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Westminster.
        /// </summary>
        internal static string ViewStartTitle {
            get {
                return ResourceManager.GetString("ViewStartTitle", resourceCulture);
            }
        }
    }
}
